# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :internal do
    upload_to_play_store(track: 'internal', aab: './build/app/outputs/bundle/playRelease/app-play-release.aab')
  end

  lane :alpha do
    pubspec = File.read('../pubspec.yaml')
    regex = /version:\s.+\+(\d+)/
    code = pubspec[regex, 1]
    
    upload_to_play_store(
      track: 'internal', 
      track_promote_to: 'alpha', 
      version_code: code.to_i,
      skip_upload_aab: 'true', 
      skip_upload_apk: 'true',
      skip_upload_metadata: 'true',
      skip_upload_images: 'true',
      skip_upload_screenshots: 'true',
    )
  end
end
